sms-admin/src/com/bon/vo/SMSVO.java
package com.bon.vo;

import java.util.Date;

import com.bon.persistence.CustomerDAO;
import com.bon.util.DateUtil;

public class SMSVO extends ObjectIdVO {
	private long userObjectId;
	private long customerObjectId;
	private long creationTimestamp;
	private long scheduledTimestamp;
	private String message;
	private boolean sent;
	
	public long getUserObjectId() {
		return userObjectId;
	}
	
	public void setUserObjectId(long userObjectId) {
		this.userObjectId = userObjectId;
	}
	
	public long getCustomerObjectId() {
		return customerObjectId;
	}
	
	public String getCustomerName() {
		return CustomerDAO.getInstance().findName(customerObjectId);
	}
	
	public void setCustomerObjectId(long customerObjectId) {
		this.customerObjectId = customerObjectId;
	}
	
	public long getCreationTimestamp() {
		return creationTimestamp;
	}
	
	public void setCreationTimestamp(long creationTimestamp) {
		this.creationTimestamp = creationTimestamp;
	}
	
	public long getScheduledTimestamp() {
		return scheduledTimestamp;
	}
	
	public String getScheduledTimestampFormatted() {
		return DateUtil.getHoursAndMinutes(scheduledTimestamp);
	}
	
	public void setScheduledTimestamp(long scheduledTimestamp) {
		this.scheduledTimestamp = scheduledTimestamp;
	}
	
	public String getMessage() {
		return message;
	}
	
	public void setMessage(String message) {
		this.message = message;
	}

	public boolean isSent() {
		return sent;
	}
	
	public boolean isScheduledTimePast() {
		return  new Date().getTime() >= scheduledTimestamp;
	}

	public void setSent(boolean sent) {
		this.sent = sent;
	}
}

sms-admin/src/com/bon/action/SMSActionBean.java
package com.bon.action;

import java.util.List;

import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.Resolution;

import com.bon.ctrl.SMSCtrl;
import com.bon.util.DateUtil;
import com.bon.vo.SMSVO;

public class SMSActionBean extends BaseActionBean {
	private long timestamp;
	private List<SMSVO> smss;
	
	@DefaultHandler
    public Resolution main() {
		if (timestamp <= 0) {
			timestamp = getCurrentTimestamp();
		}
		SMSCtrl c = SMSCtrl.getInstance();
		smss = c.findAll(getUserFromSession().getObjectId(), timestamp);
		return new ForwardResolution(JSP_DIR + "sms.jsp");
    }
	
	public String getFormattedDate() {
		return DateUtil.format(timestamp);
	}
	
	public boolean isDayPast() {
		return DateUtil.getDaysFirstTimestamp(getCurrentTimestamp()) > timestamp;
	}

	public long getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(long timestamp) {
		this.timestamp = timestamp;
	}

	public List<SMSVO> getSmss() {
		return smss;
	}

	public void setSmss(List<SMSVO> smss) {
		this.smss = smss;
	}
}

sms-admin/src/com/bon/action/SMSAddActionBean.java
package com.bon.action;

import java.util.Date;
import java.util.List;

import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.DontValidate;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.validation.SimpleError;
import net.sourceforge.stripes.validation.Validate;
import net.sourceforge.stripes.validation.ValidationErrors;
import net.sourceforge.stripes.validation.ValidationMethod;

import com.bon.ctrl.CustomerCtrl;
import com.bon.ctrl.SMSCtrl;
import com.bon.util.DateUtil;
import com.bon.vo.CustomerVO;
import com.bon.vo.SMSVO;

public class SMSAddActionBean extends BaseActionBean {
	@Validate(required=true)
	private long timestamp;
	@Validate(required=true, label="Horário")
	private String scheduledTime;
	@Validate(required=true, maxlength=160, label="Mensagem")
	private String message;
	@Validate(required=true, label="Cliente")
	private long customerObjectId;
	private long completeScheduledTime;
	
	@DontValidate
	@DefaultHandler
    public Resolution main() {
		return new ForwardResolution(JSP_DIR + "smsAdd.jsp");
    }
	
	@ValidationMethod
	public void validate(ValidationErrors errors) {
		if (DateUtil.isTimeValid(scheduledTime)) {
			completeScheduledTime = DateUtil.setFormattedTime(timestamp, scheduledTime);
			if (completeScheduledTime <= timestamp) {
				errors.addGlobalError(new SimpleError("Horário inválido"));
			}
		} else {
			errors.addGlobalError(new SimpleError("Horário inválido"));
		}
	}
	
	@Validate
	public Resolution save() {
		SMSVO vo = new SMSVO();
		vo.setCreationTimestamp(new Date().getTime());
		vo.setUserObjectId(getUserFromSession().getObjectId());
		vo.setCustomerObjectId(customerObjectId);
		vo.setMessage(message);
		vo.setScheduledTimestamp(completeScheduledTime);
		vo.setSent(false);
		SMSCtrl.getInstance().save(vo);
		return backToSMS();
    }
	
	@DontValidate
	public Resolution cancel() {
		return backToSMS();
	}
	
	private Resolution backToSMS() {
		return new ForwardResolution(SMSActionBean.class).addParameter("timestamp", timestamp);
	}

	public List<CustomerVO> getActiveCustomers() {
		CustomerCtrl c = CustomerCtrl.getInstance();
		return c.findAllActive(getUserFromSession().getObjectId());
	}

	public long getTimestamp() {
		return timestamp;
	}
	
	public String getFormattedDate() {
		return DateUtil.format(timestamp);
	}

	public void setTimestamp(long timestamp) {
		this.timestamp = timestamp;
	}

	public String getScheduledTime() {
		return scheduledTime;
	}

	public void setScheduledTime(String scheduledTime) {
		this.scheduledTime = scheduledTime;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public long getCustomerObjectId() {
		return customerObjectId;
	}

	public void setCustomerObjectId(long customerObjectId) {
		this.customerObjectId = customerObjectId;
	}
}

sms-admin/WebContent/page/jsp/customer.jsp
<%@page contentType="text/html" pageEncoding="UTF-8" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Torpedo-Avisa</title>
<link rel="stylesheet" type="text/css" href="page/css/reset.css"/>
<link rel="stylesheet" type="text/css" href="page/css/commons.css"/>
<link rel="stylesheet" type="text/css" href="page/css/css3-gmail-style.css"/>
<link rel="stylesheet" type="text/css" href="page/css/content.css"/>
<link rel="stylesheet" type="text/css" href="page/css/header.css"/>
<link rel="stylesheet" type="text/css" href="page/css/menu.css"/>
</head>
<body>
	<!-- Header -->
	<%@ include file="tiles/header.jsp" %>
	<!-- Menu -->
	<%@ include file="tiles/menu.jsp" %>
	<!-- Content -->
	<div class="content common">
		<span>Cliente</span>
		<div style="margin-top:20px;">
			<s:link class="bttn blue common" beanclass="com.bon.action.CustomerAddActionBean" event="main">Adicionar</s:link>
		</div>
		<div style="margin-top:10px; margin-right:15px; margin-bottom:15px;">
			<table class="table">
				<tr>
					<th>Ação</th>
					<th>Nome</th>
					<th>Celular</th>
				</tr>
				<c:forEach items="${actionBean.customers}" var="customer">
					<tr>
						<td class="action">
							<s:form style="width:60px;display:inline-block" beanclass="com.bon.action.CustomerEditActionBean" method="GET">
								<input type="hidden" name="customer.objectId" value="${customer.objectId}"/>
								<s:submit class="bttn" name="main">Editar</s:submit>
							</s:form>
							<s:form style="width:60px;display:inline-block" beanclass="com.bon.action.CustomerDeleteActionBean" method="GET">
								<input type="hidden" name="customer.objectId" value="${customer.objectId}"/>
								<s:submit class="bttn" name="delete" onclick="return confirm('Excluir um cliente irá cancelar todas as mensagens agendadas para esse contato. Confirma?');">Excluir</s:submit>
							</s:form>
						</td>
						<td>${customer.name}</td>
						<td>${customer.msisdn}</td>
					</tr>
				</c:forEach>
			</table>			
		</div>
	</div>
</body>
</html>

sms-admin/WebContent/page/jsp/customerAdd.jsp
<%@page contentType="text/html" pageEncoding="UTF-8" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@taglib  prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Torpedo-Avisa</title>
<link rel="stylesheet" type="text/css" href="page/css/reset.css"/>
<link rel="stylesheet" type="text/css" href="page/css/commons.css"/>
<link rel="stylesheet" type="text/css" href="page/css/css3-gmail-style.css"/>
<link rel="stylesheet" type="text/css" href="page/css/content.css"/>
<link rel="stylesheet" type="text/css" href="page/css/header.css"/>
<link rel="stylesheet" type="text/css" href="page/css/menu.css"/>
</head>
<body>
	<!-- Header -->
	<%@ include file="tiles/header.jsp" %>
	<!-- Menu -->
	<%@ include file="tiles/menu.jsp" %>
	<!-- Content -->
	<div class="content common" style="width:420px">
		<span>Cliente</span>
		<div style="margin-top:20px;">
			<span>Adicionar Cliente</span>
		</div>
		<div style="margin-top:10px; margin-right:15px; margin-bottom:15px;">
			<s:form beanclass="com.bon.action.CustomerAddActionBean" method="POST">
				<div class="margin">Nome: <s:text name="customer.name" class="textField" maxlength="84"></s:text></div>			
				<div class="margin">Celular: <s:text id="msisdn" name="customer.msisdn" class="textField" maxlength="11" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')"></s:text></div>
				<div class="margin">
					<s:submit name="save" class="bttn blue" value="Salvar"></s:submit>
					<s:submit style="margin-left:15px" name="cancel" class="bttn red" value="Cancelar"></s:submit>
				</div>
			</s:form>
		</div>
		<div><s:errors></s:errors></div>
	</div>
</body>
</html>

sms-admin/WebContent/page/jsp/customerEdit.jsp
<%@page contentType="text/html" pageEncoding="UTF-8" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@taglib  prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Torpedo-Avisa</title>
<link rel="stylesheet" type="text/css" href="page/css/reset.css"/>
<link rel="stylesheet" type="text/css" href="page/css/commons.css"/>
<link rel="stylesheet" type="text/css" href="page/css/css3-gmail-style.css"/>
<link rel="stylesheet" type="text/css" href="page/css/content.css"/>
<link rel="stylesheet" type="text/css" href="page/css/header.css"/>
<link rel="stylesheet" type="text/css" href="page/css/menu.css"/>
</head>
<body>
	<!-- Header -->
	<%@ include file="tiles/header.jsp" %>
	<!-- Menu -->
	<%@ include file="tiles/menu.jsp" %>
	<!-- Content -->
	<div class="content common" style="width:420px">
		<span>Cliente</span>
		<div style="margin-top:20px;">
			<span>Editar Cliente</span>
		</div>
		<div style="margin-top:10px; margin-right:15px; margin-bottom:15px;">
			<s:form beanclass="com.bon.action.CustomerAddActionBean" method="POST">
				<s:hidden name="customer.objectId" value="${customer.objectId}"></s:hidden>
				<div class="margin">Nome: <s:text name="customer.name" class="textField" maxlength="84" value="${actionBean.customer.name}"></s:text></div>			
				<div class="margin">Celular: <s:text id="msisdn" name="customer.msisdn" class="textField" maxlength="11" value="${actionBean.customer.msisdn}" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')"></s:text></div>
				<div class="margin">
					<s:submit name="save" class="bttn blue" value="Salvar"></s:submit>
					<s:submit style="margin-left:15px" name="cancel" class="bttn red" value="Cancelar"></s:submit>
				</div>
			</s:form>
		</div>
		<div><s:errors></s:errors></div>
	</div>
</body>
</html>

sms-admin/WebContent/page/jsp/index.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:redirect url="Login.action"/>

sms-admin/WebContent/page/jsp/login.jsp
<%@taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@page contentType="text/html" pageEncoding="UTF-8" %>
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Torpedo-Avisa</title>
<link rel="stylesheet" type="text/css" href="page/css/reset.css"/>
<link rel="stylesheet" type="text/css" href="page/css/commons.css"/>
<link rel="stylesheet" type="text/css" href="page/css/css3-gmail-style.css"/>
<link rel="stylesheet" type="text/css" href="page/css/login.css"/>
</head>
<body>
	<div id="logo" class="center margin"></div>
	<div class="center formPanel">
		<p class="common center formText">Login</p>
		<div class="center form">
			<s:form beanclass="com.bon.action.LoginActionBean" method="POST">
				<p class="common bold margin">Email:</p>
				<s:text class="textField" id="email" name="email"></s:text>
				<p class="common bold margin">Senha:</p>
				<s:password class="textField" id="password" name="password"></s:password>
				<br/>
				<s:submit name="login" class="bttn blue margin" value="Login"></s:submit>
				<a class="common" href="#">Não consegue acessar?</a>
				<s:errors></s:errors>
			</s:form>
		</div>
	</div>
</body>
</html>

sms-admin/WebContent/page/jsp/sms.jsp
<%@page contentType="text/html" pageEncoding="UTF-8" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Torpedo-Avisa</title>
<link rel="stylesheet" type="text/css" href="page/css/reset.css"/>
<link rel="stylesheet" type="text/css" href="page/css/commons.css"/>
<link rel="stylesheet" type="text/css" href="page/css/css3-gmail-style.css"/>
<link rel="stylesheet" type="text/css" href="page/css/content.css"/>
<link rel="stylesheet" type="text/css" href="page/css/header.css"/>
<link rel="stylesheet" type="text/css" href="page/css/menu.css"/>
</head>
<body>
	<!-- Header -->
	<%@ include file="tiles/header.jsp" %>
	<!-- Menu -->
	<%@ include file="tiles/menu.jsp" %>
	<!-- Content -->
	<div class="content common">
		<span>SMS</span>
		<div style="margin-top:20px;">
			<span>Agenda para envios de sms do dia <a style="font-weight:bold" href="#" id="timestamp">${actionBean.formattedDate}</a>. Clique na data para visualizar outras.</span>
		</div>
		<div style="margin-top:20px;">
			<c:if test="${not actionBean.dayPast}">
				<s:link class="bttn blue common" beanclass="com.bon.action.SMSAddActionBean" event="main">
					<s:param name="timestamp" value="${actionBean.timestamp}"/> 
					Adicionar
				</s:link>
			</c:if>
		</div>
		<div style="margin-top:10px; margin-right:15px; margin-bottom:15px;">
			<table class="table">
				<tr>
					<th>Ação</th>
					<th>Horário</th>
					<th>Cliente</th>
					<th>Mensagem</th>
				</tr>
				<c:forEach items="${actionBean.smss}" var="sms">
					<tr>
						<td class="action">
							<c:if test="${not sms.scheduledTimePast}">
								<s:form style="width:60px;display:inline-block" beanclass="com.bon.action.SMSEditActionBean" method="GET">
									<input type="hidden" name="objectId" value="${sms.objectId}"/>
									<input type="hidden" name="timestamp" value="${actionBean.timestamp}"/>
									<s:submit class="bttn" name="main">Editar</s:submit>
								</s:form>
								<s:form style="width:60px;display:inline-block" beanclass="com.bon.action.SMSDeleteActionBean" method="GET">
									<input type="hidden" name="objectId" value="${sms.objectId}"/>
									<input type="hidden" name="timestamp" value="${actionBean.timestamp}"/>
									<input type="hidden" name="scheduledTimestamp" value="${sms.scheduledTimestamp}"/>
									<s:submit class="bttn" name="delete" onclick="return confirm('Confirma a exclusão?');">Excluir</s:submit>
								</s:form>
							</c:if>
						</td>
						<td>${sms.scheduledTimestampFormatted}</td>
						<td class="customer">${sms.customerName}</td>
						<td class="message">${sms.message}</td>
					</tr>
				</c:forEach>
			</table>			
		</div>
	</div>
<script type="text/javascript" src="page/js/plugin/scw.js"></script>
<script type="text/javascript" src="page/js/plugin/jquery-1.8.0.min.js"></script>
<script type="text/javascript" src="page/js/sms.js"></script>
</body>
</html>

sms-admin/WebContent/page/jsp/smsAdd.jsp
<%@page contentType="text/html" pageEncoding="UTF-8" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@taglib  prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Torpedo-Avisa</title>
<link rel="stylesheet" type="text/css" href="page/css/reset.css"/>
<link rel="stylesheet" type="text/css" href="page/css/commons.css"/>
<link rel="stylesheet" type="text/css" href="page/css/css3-gmail-style.css"/>
<link rel="stylesheet" type="text/css" href="page/css/content.css"/>
<link rel="stylesheet" type="text/css" href="page/css/header.css"/>
<link rel="stylesheet" type="text/css" href="page/css/menu.css"/>
</head>
<body>
	<!-- Header -->
	<%@ include file="tiles/header.jsp" %>
	<!-- Menu -->
	<%@ include file="tiles/menu.jsp" %>
	<!-- Content -->
	<div class="content common" style="width:420px">
		<span>SMS</span>
		<div style="margin-top:20px;">
			<span>Adicionar SMS para o dia ${actionBean.formattedDate}</span>
		</div>
		<div style="margin-top:10px; margin-right:15px; margin-bottom:15px;">
			<s:form beanclass="com.bon.action.SMSAddActionBean" method="POST">
				<s:hidden name="timestamp" value="${actionBean.timestamp}"></s:hidden>
				<div class="margin">Horário: <s:text id="scheduledTime" style="width:40px" name="scheduledTime" class="textField"></s:text></div>			
				<div class="margin">Cliente: 
					<s:select name="customerObjectId" class="textField">					
						<s:option value="">Selecione</s:option>
						<s:options-collection collection="${actionBean.activeCustomers}" value="objectId" label="name" sort="name"/>
					</s:select>
				</div>
				<c:set var="messageLength" value="${fn:length(actionBean.message)}"></c:set>
				<div class="margin">Mensagem - <span id="counter">${160 - messageLength}</span>:</div>
				<s:textarea class="textField" id="messageBox" name="message" style="width:400px; height:100px"></s:textarea>
				<div class="margin">
					<s:submit name="save" class="bttn blue" value="Salvar"></s:submit>
					<s:submit style="margin-left:15px" name="cancel" class="bttn red" value="Cancelar"></s:submit>
				</div>
			</s:form>
		</div>
		<div><s:errors></s:errors></div>
	</div>
<script type="text/javascript" src="page/js/plugin/jquery-1.8.0.min.js"></script>
<script type="text/javascript" src="page/js/plugin/jquery.maskedinput-1.2.2.js"></script>
<script type="text/javascript" src="page/js/smsEdit.js"></script>
</body>
</html>

sms-admin/WebContent/page/jsp/smsEdit.jsp
<%@page contentType="text/html" pageEncoding="UTF-8" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@taglib  prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Torpedo-Avisa</title>
<link rel="stylesheet" type="text/css" href="page/css/reset.css"/>
<link rel="stylesheet" type="text/css" href="page/css/commons.css"/>
<link rel="stylesheet" type="text/css" href="page/css/css3-gmail-style.css"/>
<link rel="stylesheet" type="text/css" href="page/css/content.css"/>
<link rel="stylesheet" type="text/css" href="page/css/header.css"/>
<link rel="stylesheet" type="text/css" href="page/css/menu.css"/>
</head>
<body>
	<!-- Header -->
	<%@ include file="tiles/header.jsp" %>
	<!-- Menu -->
	<%@ include file="tiles/menu.jsp" %>
	<!-- Content -->
	<div class="content common" style="width:420px">
		<span>SMS</span>
		<div style="margin-top:20px;">
			<span>Editar SMS para o dia ${actionBean.formattedDate}</span>
		</div>
		<div style="margin-top:10px; margin-right:15px; margin-bottom:15px;">
			<s:form beanclass="com.bon.action.SMSEditActionBean" method="POST">
				<s:hidden name="timestamp" value="${actionBean.timestamp}"></s:hidden>
				<s:hidden name="objectId" value="${actionBean.objectId}"></s:hidden>
				<div class="margin">Horário: <s:text id="scheduledTime" style="width:40px" name="scheduledTime" class="textField" value="${actionBean.sms.scheduledTimestampFormatted}"></s:text></div>			
				<div class="margin">Cliente: 
					<select name="customerObjectId" class="textField">
						<c:forEach items="${actionBean.activeCustomers}" var="customer">
							<c:set var="checked" value="${actionBean.sms.customerObjectId == customer.objectId}"/>
							<c:choose>
								<c:when test="${checked}">
									<option selected value="${customer.objectId}">${customer.name}</option>
								</c:when>
								<c:otherwise>
									<option value="${customer.objectId}">${customer.name}</option>
								</c:otherwise>
							</c:choose>
						</c:forEach>
					</select>
				</div>
				<c:set var="messageLength" value="${fn:length(actionBean.sms.message)}"></c:set>
				<c:if test="${messageLength == 0}">
					<c:set var="messageLength" value="${fn:length(actionBean.message)}"></c:set>
				</c:if>
				<div class="margin">Mensagem - <span id="counter">${160 - messageLength}</span>:</div>
				<s:textarea class="textField" id="messageBox" name="message" style="width:400px; height:100px" value="${actionBean.sms.message}"></s:textarea>
				<div class="margin">
					<s:submit name="save" class="bttn blue" value="Salvar"></s:submit>
					<s:submit style="margin-left:15px" name="cancel" class="bttn red" value="Cancelar"></s:submit>
				</div>
			</s:form>
		</div>
		<div><s:errors></s:errors></div>
	</div>
<script type="text/javascript" src="page/js/plugin/jquery-1.8.0.min.js"></script>
<script type="text/javascript" src="page/js/plugin/jquery.maskedinput-1.2.2.js"></script>
<script type="text/javascript" src="page/js/smsEdit.js"></script>
</body>
</html>